[RELIANCE, HDFCBANK, ITC, HINDUNILVR, HDFC, SBIN, ONGC,
  LT, ICICIBANK, TATAMOTORS, NTPC, SUNPHARMA, BHARTIARTL,
  TCS,MOTHERSUMI ,PIDILITIND ,PAGEIND ,WABCOINDIA ,TITAN ,
  MRF ,JUBLFOOD ,KOTAKBANK , MM ,POWERGRID ,INFY ,COLPAL ,
  GILLETTE ,MARICO ,BRITANNIA ,TATASTEEL ,ASIANPAINT,HAVELLS,
  CADILAHC,PETRONET,NESTLEIND,BAJFINANCE,BPCL,CIPLA,SCHAEFFLER,
  UPL,PGHH,GAIL,AUROPHARMA,AXISBANK, COALINDIA, HINDALCO, 
  YESBANK,AMBUJACEM,INDIGO,CONCOR,FRETAIL,FINCABLES,RBLBANK,GLAXO,
  ZEEL,GRUH,INDUSINDBK,MINDTREE,DMART,SHREECEM,SUPREMEIND,
  TATACHEM,HCL_TECH,GRASIM,CHOLAFIN,FEDERALBNK, DIVISLAB,DRREDDY]