[NSE/RELIANCE, NSE/HDFCBANK, NSE/ITC, NSE/HINDUNILVR, NSE/HDFC, NSE/SBIN, NSE/ONGC,
  NSE/LT, NSE/ICICIBANK, NSE/TATAMOTORS, NSE/NTPC, NSE/SUNPHARMA, NSE/BHARTIARTL,
  NSE/TCS,NSE/MOTHERSUMI ,NSE/PIDILITIND ,NSE/PAGEIND ,NSE/WABCOINDIA ,NSE/TITAN ,
  NSE/MRF ,NSE/JUBLFOOD ,NSE/KOTAKBANK , NSE/MM ,NSE/POWERGRID ,NSE/INFY ,NSE/COLPAL ,
  NSE/GILLETTE ,NSE/MARICO ,NSE/BRITANNIA ,NSE/TATASTEEL ,NSE/ASIANPAINT,NSE/HAVELLS,
  NSE/CADILAHC,NSE/PETRONET,NSE/NESTLEIND,NSE/BAJFINANCE,NSE/BPCL,NSE/CIPLA,NSE/SCHAEFFLER,
  NSE/UPL,NSE/PGHH,NSE/GAIL,NSE/AUROPHARMA,NSE/AXISBANK, NSE/COALINDIA, NSE/HINDALCO, 
  NSE/YESBANK,NSE/AMBUJACEM,NSE/INDIGO,NSE/CONCOR,NSE/FRETAIL,NSE/FINCABLES,NSE/RBLBANK,NSE/GLAXO,
  NSE/ZEEL,NSE/GRUH,NSE/INDUSINDBK,NSE/MINDTREE,NSE/DMART,NSE/SHREECEM,NSE/SUPREMEIND,
  NSE/TATACHEM,NSE/HCL_INSYS,NSE/GRASIM,NSE/CHOLAFIN,NSE/FEDERALBNK, NSE/DIVISLAB,NSE/DRREDDY]